"""Change Chat column from query to prompt

Revision ID: 6105749ffa89
Revises: b6ce25662e2d
Create Date: 2025-10-20 19:31:45.626712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6105749ffa89'
down_revision = 'b6ce25662e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.Text(), nullable=False))
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
