"""Make response column nullable

Revision ID: 9f0dbc569fe3
Revises: 6105749ffa89
Create Date: 2025-10-24 20:21:14.103150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0dbc569fe3'
down_revision = '6105749ffa89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
