"""Change chat columns name

Revision ID: b88e5bea358a
Revises: 9f0dbc569fe3
Create Date: 2025-10-24 20:38:59.146664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88e5bea358a'
down_revision = '9f0dbc569fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_prompt', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('llm_response', sa.Text(), nullable=True))
        batch_op.drop_column('prompt')
        batch_op.drop_column('response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('llm_response')
        batch_op.drop_column('user_prompt')

    # ### end Alembic commands ###
